apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyApi-deployment
  labels:
    app: myapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapi  
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: myapi:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myacrcredentails
---
apiVersion: v1
kind: Service
metadata:
  name: myapisvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: myapi